// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: api.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OutfluxClient is the client API for Outflux service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutfluxClient interface {
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type outfluxClient struct {
	cc grpc.ClientConnInterface
}

func NewOutfluxClient(cc grpc.ClientConnInterface) OutfluxClient {
	return &outfluxClient{cc}
}

func (c *outfluxClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/Outflux/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutfluxServer is the server API for Outflux service.
// All implementations must embed UnimplementedOutfluxServer
// for forward compatibility
type OutfluxServer interface {
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	mustEmbedUnimplementedOutfluxServer()
}

// UnimplementedOutfluxServer must be embedded to have forward compatible implementations.
type UnimplementedOutfluxServer struct {
}

func (UnimplementedOutfluxServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedOutfluxServer) mustEmbedUnimplementedOutfluxServer() {}

// UnsafeOutfluxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutfluxServer will
// result in compilation errors.
type UnsafeOutfluxServer interface {
	mustEmbedUnimplementedOutfluxServer()
}

func RegisterOutfluxServer(s grpc.ServiceRegistrar, srv OutfluxServer) {
	s.RegisterService(&Outflux_ServiceDesc, srv)
}

func _Outflux_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutfluxServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Outflux/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutfluxServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Outflux_ServiceDesc is the grpc.ServiceDesc for Outflux service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Outflux_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Outflux",
	HandlerType: (*OutfluxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _Outflux_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
